### ISSUE TITLE
How I do the onclick item?

### ISSUE THREAD

**Issue by RodolfoMota** [softsan/HorizontalListView#2]
How I do the onclick item?

**Comment by softsan** [comment]
if you follow the MVVM pattern, there is a ICommand which you can use to bind your execution with Command property.
protected readonly ICommand SelectedCommand;

You can also define OnItemclick event in the horizontal list and exposed it to outside and then invoke your code on that event. ( i would certainly like to expose that event, but currently don't have much time). 

Alternatively, you can define data template which can include a button and then on click of it, you can execute your code. 

you can also create ContentView and bind it with ItemTemplate and expose "OnTap" event.
eg.

```
 public partial class CustomDataTemplate : ContentView
    {
        public event EventHandler<YourModel> OnTap; 

		public CustomDataTemplate()
		{
			InitializeComponent();
		}

        void Tap(object sender, EventArgs e)
        {
            if (OnTap != null)
            {
                OnTap(sender, this.BindingContext as YourModel);
            }
        }
	}
```
**Xaml:**

//XmlNS
 `xmlns:views="clr-namespace:YourNameSpace.Views;assembly=YourAssembly"`
 
```
 <controls:HorizontalListView
                            ItemsSource="{Binding Categories}"
                            ListOrientation="Horizontal" 
                            HorizontalOptions="Fill">
                            <controls: HorizontalListView.ItemTemplate>
                                <DataTemplate>
                                    <views:CustomDataTemplate OnTap="OnItemTapped" />
                                </DataTemplate>
                            </controls: HorizontalListView.ItemTemplate>
                        </controls:HorizontalListView>
```
                     
**in your page**:
```
void OnItemTapped(object sender, YourModel model)
{
  // you can access properties through the model
}
```

**Comment by RodolfoMota** [comment]
Ty.
